import type { MapKey } from './i18n'

/* Display names for every feature in every committed atlas, keyed by the
   atlas's OWN name for that feature (English in world/us, bare Chinese in
   china). The engine renders NAMES[map][featureName][locale], so a region
   reads in the page's language whether or not it has been visited.

   Coverage is not optional: scripts/check-data.mjs fails the build if an
   atlas feature has no entry here, or if an entry disagrees with the
   Chinese label a visited place carries in lib/data.ts. Without that gate
   a new atlas would silently reintroduce the mixed-language tooltips this
   table exists to remove.

   The `en` value is a display name, not an echo of the key — the atlases
   abbreviate ("Bosnia and Herz.", "Dem. Rep. Congo"), and this is where
   those get spelled out. */

export interface RegionName {
  en: string
  zh: string
}

export const NAMES: Record<MapKey, Record<string, RegionName>> = {
  world: {
    Afghanistan: { en: 'Afghanistan', zh: '阿富汗' },
    Albania: { en: 'Albania', zh: '阿尔巴尼亚' },
    Algeria: { en: 'Algeria', zh: '阿尔及利亚' },
    Angola: { en: 'Angola', zh: '安哥拉' },
    Antarctica: { en: 'Antarctica', zh: '南极洲' },
    Argentina: { en: 'Argentina', zh: '阿根廷' },
    Armenia: { en: 'Armenia', zh: '亚美尼亚' },
    Australia: { en: 'Australia', zh: '澳大利亚' },
    Austria: { en: 'Austria', zh: '奥地利' },
    Azerbaijan: { en: 'Azerbaijan', zh: '阿塞拜疆' },
    Bahamas: { en: 'Bahamas', zh: '巴哈马' },
    Bangladesh: { en: 'Bangladesh', zh: '孟加拉国' },
    Belarus: { en: 'Belarus', zh: '白俄罗斯' },
    Belgium: { en: 'Belgium', zh: '比利时' },
    Belize: { en: 'Belize', zh: '伯利兹' },
    Benin: { en: 'Benin', zh: '贝宁' },
    Bhutan: { en: 'Bhutan', zh: '不丹' },
    Bolivia: { en: 'Bolivia', zh: '玻利维亚' },
    'Bosnia and Herz.': { en: 'Bosnia and Herzegovina', zh: '波斯尼亚和黑塞哥维那' },
    Botswana: { en: 'Botswana', zh: '博茨瓦纳' },
    Brazil: { en: 'Brazil', zh: '巴西' },
    Brunei: { en: 'Brunei', zh: '文莱' },
    Bulgaria: { en: 'Bulgaria', zh: '保加利亚' },
    'Burkina Faso': { en: 'Burkina Faso', zh: '布基纳法索' },
    Burundi: { en: 'Burundi', zh: '布隆迪' },
    Cambodia: { en: 'Cambodia', zh: '柬埔寨' },
    Cameroon: { en: 'Cameroon', zh: '喀麦隆' },
    Canada: { en: 'Canada', zh: '加拿大' },
    'Central African Rep.': { en: 'Central African Republic', zh: '中非共和国' },
    Chad: { en: 'Chad', zh: '乍得' },
    Chile: { en: 'Chile', zh: '智利' },
    China: { en: 'China', zh: '中国' },
    Colombia: { en: 'Colombia', zh: '哥伦比亚' },
    Congo: { en: 'Republic of the Congo', zh: '刚果共和国' },
    'Costa Rica': { en: 'Costa Rica', zh: '哥斯达黎加' },
    Croatia: { en: 'Croatia', zh: '克罗地亚' },
    Cuba: { en: 'Cuba', zh: '古巴' },
    Cyprus: { en: 'Cyprus', zh: '塞浦路斯' },
    Czechia: { en: 'Czechia', zh: '捷克' },
    "Côte d'Ivoire": { en: "Côte d'Ivoire", zh: '科特迪瓦' },
    'Dem. Rep. Congo': { en: 'Democratic Republic of the Congo', zh: '刚果民主共和国' },
    Denmark: { en: 'Denmark', zh: '丹麦' },
    Djibouti: { en: 'Djibouti', zh: '吉布提' },
    'Dominican Rep.': { en: 'Dominican Republic', zh: '多米尼加共和国' },
    Ecuador: { en: 'Ecuador', zh: '厄瓜多尔' },
    Egypt: { en: 'Egypt', zh: '埃及' },
    'El Salvador': { en: 'El Salvador', zh: '萨尔瓦多' },
    'Eq. Guinea': { en: 'Equatorial Guinea', zh: '赤道几内亚' },
    Eritrea: { en: 'Eritrea', zh: '厄立特里亚' },
    Estonia: { en: 'Estonia', zh: '爱沙尼亚' },
    Ethiopia: { en: 'Ethiopia', zh: '埃塞俄比亚' },
    'Falkland Is.': { en: 'Falkland Islands', zh: '福克兰群岛' },
    Fiji: { en: 'Fiji', zh: '斐济' },
    Finland: { en: 'Finland', zh: '芬兰' },
    'Fr. S. Antarctic Lands': {
      en: 'French Southern and Antarctic Lands',
      zh: '法属南部和南极领地'
    },
    France: { en: 'France', zh: '法国' },
    Gabon: { en: 'Gabon', zh: '加蓬' },
    Gambia: { en: 'Gambia', zh: '冈比亚' },
    Georgia: { en: 'Georgia', zh: '格鲁吉亚' },
    Germany: { en: 'Germany', zh: '德国' },
    Ghana: { en: 'Ghana', zh: '加纳' },
    Greece: { en: 'Greece', zh: '希腊' },
    Greenland: { en: 'Greenland', zh: '格陵兰' },
    Guatemala: { en: 'Guatemala', zh: '危地马拉' },
    Guinea: { en: 'Guinea', zh: '几内亚' },
    'Guinea-Bissau': { en: 'Guinea-Bissau', zh: '几内亚比绍' },
    Guyana: { en: 'Guyana', zh: '圭亚那' },
    Haiti: { en: 'Haiti', zh: '海地' },
    Honduras: { en: 'Honduras', zh: '洪都拉斯' },
    Hungary: { en: 'Hungary', zh: '匈牙利' },
    Iceland: { en: 'Iceland', zh: '冰岛' },
    India: { en: 'India', zh: '印度' },
    Indonesia: { en: 'Indonesia', zh: '印度尼西亚' },
    Iran: { en: 'Iran', zh: '伊朗' },
    Iraq: { en: 'Iraq', zh: '伊拉克' },
    Ireland: { en: 'Ireland', zh: '爱尔兰' },
    Israel: { en: 'Israel', zh: '以色列' },
    Italy: { en: 'Italy', zh: '意大利' },
    Jamaica: { en: 'Jamaica', zh: '牙买加' },
    Japan: { en: 'Japan', zh: '日本' },
    Jordan: { en: 'Jordan', zh: '约旦' },
    Kazakhstan: { en: 'Kazakhstan', zh: '哈萨克斯坦' },
    Kenya: { en: 'Kenya', zh: '肯尼亚' },
    Kosovo: { en: 'Kosovo', zh: '科索沃' },
    Kuwait: { en: 'Kuwait', zh: '科威特' },
    Kyrgyzstan: { en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦' },
    Laos: { en: 'Laos', zh: '老挝' },
    Latvia: { en: 'Latvia', zh: '拉脱维亚' },
    Lebanon: { en: 'Lebanon', zh: '黎巴嫩' },
    Lesotho: { en: 'Lesotho', zh: '莱索托' },
    Liberia: { en: 'Liberia', zh: '利比里亚' },
    Libya: { en: 'Libya', zh: '利比亚' },
    Lithuania: { en: 'Lithuania', zh: '立陶宛' },
    Luxembourg: { en: 'Luxembourg', zh: '卢森堡' },
    Macedonia: { en: 'North Macedonia', zh: '北马其顿' },
    Madagascar: { en: 'Madagascar', zh: '马达加斯加' },
    Malawi: { en: 'Malawi', zh: '马拉维' },
    Malaysia: { en: 'Malaysia', zh: '马来西亚' },
    Mali: { en: 'Mali', zh: '马里' },
    Mauritania: { en: 'Mauritania', zh: '毛里塔尼亚' },
    Mexico: { en: 'Mexico', zh: '墨西哥' },
    Moldova: { en: 'Moldova', zh: '摩尔多瓦' },
    Mongolia: { en: 'Mongolia', zh: '蒙古' },
    Montenegro: { en: 'Montenegro', zh: '黑山' },
    Morocco: { en: 'Morocco', zh: '摩洛哥' },
    Mozambique: { en: 'Mozambique', zh: '莫桑比克' },
    Myanmar: { en: 'Myanmar', zh: '缅甸' },
    'N. Cyprus': { en: 'Northern Cyprus', zh: '北塞浦路斯' },
    Namibia: { en: 'Namibia', zh: '纳米比亚' },
    Nepal: { en: 'Nepal', zh: '尼泊尔' },
    Netherlands: { en: 'Netherlands', zh: '荷兰' },
    'New Caledonia': { en: 'New Caledonia', zh: '新喀里多尼亚' },
    'New Zealand': { en: 'New Zealand', zh: '新西兰' },
    Nicaragua: { en: 'Nicaragua', zh: '尼加拉瓜' },
    Niger: { en: 'Niger', zh: '尼日尔' },
    Nigeria: { en: 'Nigeria', zh: '尼日利亚' },
    'North Korea': { en: 'North Korea', zh: '朝鲜' },
    Norway: { en: 'Norway', zh: '挪威' },
    Oman: { en: 'Oman', zh: '阿曼' },
    Pakistan: { en: 'Pakistan', zh: '巴基斯坦' },
    Palestine: { en: 'Palestine', zh: '巴勒斯坦' },
    Panama: { en: 'Panama', zh: '巴拿马' },
    'Papua New Guinea': { en: 'Papua New Guinea', zh: '巴布亚新几内亚' },
    Paraguay: { en: 'Paraguay', zh: '巴拉圭' },
    Peru: { en: 'Peru', zh: '秘鲁' },
    Philippines: { en: 'Philippines', zh: '菲律宾' },
    Poland: { en: 'Poland', zh: '波兰' },
    Portugal: { en: 'Portugal', zh: '葡萄牙' },
    'Puerto Rico': { en: 'Puerto Rico', zh: '波多黎各' },
    Qatar: { en: 'Qatar', zh: '卡塔尔' },
    Romania: { en: 'Romania', zh: '罗马尼亚' },
    Russia: { en: 'Russia', zh: '俄罗斯' },
    Rwanda: { en: 'Rwanda', zh: '卢旺达' },
    'S. Sudan': { en: 'South Sudan', zh: '南苏丹' },
    'Saudi Arabia': { en: 'Saudi Arabia', zh: '沙特阿拉伯' },
    Senegal: { en: 'Senegal', zh: '塞内加尔' },
    Serbia: { en: 'Serbia', zh: '塞尔维亚' },
    'Sierra Leone': { en: 'Sierra Leone', zh: '塞拉利昂' },
    Slovakia: { en: 'Slovakia', zh: '斯洛伐克' },
    Slovenia: { en: 'Slovenia', zh: '斯洛文尼亚' },
    'Solomon Is.': { en: 'Solomon Islands', zh: '所罗门群岛' },
    Somalia: { en: 'Somalia', zh: '索马里' },
    Somaliland: { en: 'Somaliland', zh: '索马里兰' },
    'South Africa': { en: 'South Africa', zh: '南非' },
    'South Korea': { en: 'South Korea', zh: '韩国' },
    Spain: { en: 'Spain', zh: '西班牙' },
    'Sri Lanka': { en: 'Sri Lanka', zh: '斯里兰卡' },
    Sudan: { en: 'Sudan', zh: '苏丹' },
    Suriname: { en: 'Suriname', zh: '苏里南' },
    Sweden: { en: 'Sweden', zh: '瑞典' },
    Switzerland: { en: 'Switzerland', zh: '瑞士' },
    Syria: { en: 'Syria', zh: '叙利亚' },
    Taiwan: { en: 'Taiwan', zh: '台湾' },
    Tajikistan: { en: 'Tajikistan', zh: '塔吉克斯坦' },
    Tanzania: { en: 'Tanzania', zh: '坦桑尼亚' },
    Thailand: { en: 'Thailand', zh: '泰国' },
    'Timor-Leste': { en: 'Timor-Leste', zh: '东帝汶' },
    Togo: { en: 'Togo', zh: '多哥' },
    'Trinidad and Tobago': { en: 'Trinidad and Tobago', zh: '特立尼达和多巴哥' },
    Tunisia: { en: 'Tunisia', zh: '突尼斯' },
    Turkey: { en: 'Turkey', zh: '土耳其' },
    Turkmenistan: { en: 'Turkmenistan', zh: '土库曼斯坦' },
    Uganda: { en: 'Uganda', zh: '乌干达' },
    Ukraine: { en: 'Ukraine', zh: '乌克兰' },
    'United Arab Emirates': { en: 'United Arab Emirates', zh: '阿拉伯联合酋长国' },
    'United Kingdom': { en: 'United Kingdom', zh: '英国' },
    'United States of America': { en: 'United States', zh: '美国' },
    Uruguay: { en: 'Uruguay', zh: '乌拉圭' },
    Uzbekistan: { en: 'Uzbekistan', zh: '乌兹别克斯坦' },
    Vanuatu: { en: 'Vanuatu', zh: '瓦努阿图' },
    Venezuela: { en: 'Venezuela', zh: '委内瑞拉' },
    Vietnam: { en: 'Vietnam', zh: '越南' },
    'W. Sahara': { en: 'Western Sahara', zh: '西撒哈拉' },
    Yemen: { en: 'Yemen', zh: '也门' },
    Zambia: { en: 'Zambia', zh: '赞比亚' },
    Zimbabwe: { en: 'Zimbabwe', zh: '津巴布韦' },
    eSwatini: { en: 'Eswatini', zh: '埃斯瓦蒂尼' }
  },

  china: {
    上海: { en: 'Shanghai', zh: '上海' },
    云南: { en: 'Yunnan', zh: '云南' },
    内蒙古: { en: 'Inner Mongolia', zh: '内蒙古' },
    北京: { en: 'Beijing', zh: '北京' },
    南海诸岛: { en: 'South China Sea Islands', zh: '南海诸岛' },
    台湾: { en: 'Taiwan', zh: '台湾' },
    吉林: { en: 'Jilin', zh: '吉林' },
    四川: { en: 'Sichuan', zh: '四川' },
    天津: { en: 'Tianjin', zh: '天津' },
    宁夏: { en: 'Ningxia', zh: '宁夏' },
    安徽: { en: 'Anhui', zh: '安徽' },
    山东: { en: 'Shandong', zh: '山东' },
    山西: { en: 'Shanxi', zh: '山西' },
    广东: { en: 'Guangdong', zh: '广东' },
    广西: { en: 'Guangxi', zh: '广西' },
    新疆: { en: 'Xinjiang', zh: '新疆' },
    江苏: { en: 'Jiangsu', zh: '江苏' },
    江西: { en: 'Jiangxi', zh: '江西' },
    河北: { en: 'Hebei', zh: '河北' },
    河南: { en: 'Henan', zh: '河南' },
    浙江: { en: 'Zhejiang', zh: '浙江' },
    海南: { en: 'Hainan', zh: '海南' },
    湖北: { en: 'Hubei', zh: '湖北' },
    湖南: { en: 'Hunan', zh: '湖南' },
    澳门: { en: 'Macau', zh: '澳门' },
    甘肃: { en: 'Gansu', zh: '甘肃' },
    福建: { en: 'Fujian', zh: '福建' },
    西藏: { en: 'Tibet', zh: '西藏' },
    贵州: { en: 'Guizhou', zh: '贵州' },
    辽宁: { en: 'Liaoning', zh: '辽宁' },
    重庆: { en: 'Chongqing', zh: '重庆' },
    /* 陕西 Shaanxi and 山西 Shanxi differ by one letter in romanisation —
       the doubled 'a' is what keeps them apart. */
    陕西: { en: 'Shaanxi', zh: '陕西' },
    青海: { en: 'Qinghai', zh: '青海' },
    香港: { en: 'Hong Kong', zh: '香港' },
    黑龙江: { en: 'Heilongjiang', zh: '黑龙江' }
  },

  us: {
    Alabama: { en: 'Alabama', zh: '亚拉巴马' },
    Alaska: { en: 'Alaska', zh: '阿拉斯加' },
    'American Samoa': { en: 'American Samoa', zh: '美属萨摩亚' },
    Arizona: { en: 'Arizona', zh: '亚利桑那' },
    Arkansas: { en: 'Arkansas', zh: '阿肯色' },
    California: { en: 'California', zh: '加利福尼亚' },
    Colorado: { en: 'Colorado', zh: '科罗拉多' },
    'Commonwealth of the Northern Mariana Islands': {
      en: 'Northern Mariana Islands',
      zh: '北马里亚纳群岛'
    },
    Connecticut: { en: 'Connecticut', zh: '康涅狄格' },
    Delaware: { en: 'Delaware', zh: '特拉华' },
    'District of Columbia': { en: 'District of Columbia', zh: '哥伦比亚特区' },
    Florida: { en: 'Florida', zh: '佛罗里达' },
    Georgia: { en: 'Georgia', zh: '佐治亚' },
    Guam: { en: 'Guam', zh: '关岛' },
    Hawaii: { en: 'Hawaii', zh: '夏威夷' },
    Idaho: { en: 'Idaho', zh: '爱达荷' },
    Illinois: { en: 'Illinois', zh: '伊利诺伊' },
    Indiana: { en: 'Indiana', zh: '印第安纳' },
    Iowa: { en: 'Iowa', zh: '艾奥瓦' },
    Kansas: { en: 'Kansas', zh: '堪萨斯' },
    Kentucky: { en: 'Kentucky', zh: '肯塔基' },
    Louisiana: { en: 'Louisiana', zh: '路易斯安那' },
    Maine: { en: 'Maine', zh: '缅因' },
    Maryland: { en: 'Maryland', zh: '马里兰' },
    Massachusetts: { en: 'Massachusetts', zh: '马萨诸塞' },
    Michigan: { en: 'Michigan', zh: '密歇根' },
    Minnesota: { en: 'Minnesota', zh: '明尼苏达' },
    Mississippi: { en: 'Mississippi', zh: '密西西比' },
    Missouri: { en: 'Missouri', zh: '密苏里' },
    Montana: { en: 'Montana', zh: '蒙大拿' },
    Nebraska: { en: 'Nebraska', zh: '内布拉斯加' },
    Nevada: { en: 'Nevada', zh: '内华达' },
    'New Hampshire': { en: 'New Hampshire', zh: '新罕布什尔' },
    'New Jersey': { en: 'New Jersey', zh: '新泽西' },
    'New Mexico': { en: 'New Mexico', zh: '新墨西哥' },
    'New York': { en: 'New York', zh: '纽约' },
    'North Carolina': { en: 'North Carolina', zh: '北卡罗来纳' },
    'North Dakota': { en: 'North Dakota', zh: '北达科他' },
    Ohio: { en: 'Ohio', zh: '俄亥俄' },
    Oklahoma: { en: 'Oklahoma', zh: '俄克拉何马' },
    Oregon: { en: 'Oregon', zh: '俄勒冈' },
    Pennsylvania: { en: 'Pennsylvania', zh: '宾夕法尼亚' },
    'Puerto Rico': { en: 'Puerto Rico', zh: '波多黎各' },
    'Rhode Island': { en: 'Rhode Island', zh: '罗得岛' },
    'South Carolina': { en: 'South Carolina', zh: '南卡罗来纳' },
    'South Dakota': { en: 'South Dakota', zh: '南达科他' },
    Tennessee: { en: 'Tennessee', zh: '田纳西' },
    Texas: { en: 'Texas', zh: '得克萨斯' },
    'United States Virgin Islands': { en: 'U.S. Virgin Islands', zh: '美属维尔京群岛' },
    Utah: { en: 'Utah', zh: '犹他' },
    Vermont: { en: 'Vermont', zh: '佛蒙特' },
    Virginia: { en: 'Virginia', zh: '弗吉尼亚' },
    Washington: { en: 'Washington', zh: '华盛顿' },
    'West Virginia': { en: 'West Virginia', zh: '西弗吉尼亚' },
    Wisconsin: { en: 'Wisconsin', zh: '威斯康星' },
    Wyoming: { en: 'Wyoming', zh: '怀俄明' }
  }
}
